import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationGuardProvider } from "next-navigation-guard";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="min-h-full">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
				<NavigationGuardProvider>
					<div className="w-auto mx-3">{children}</div>
				</NavigationGuardProvider>
			</body>
		</html>
	);
}
